//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soccer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Position { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual Teams Teams { get; set; }
        // Teams - является виртуальным, благодаря чему включается функция отложенной загрузки Entity Framework. 
        // Отложенная загрузка означает, что содержимое свойства автоматически загружается из базы данных при попытке доступа к нему.
    }
}
