//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACULTY()
        {
            this.DEPARTMENT = new HashSet<DEPARTMENT>();
        }
    
        public int FacPK { get; set; }
        public string Name { get; set; }
        public string Dean { get; set; }
        public string Building { get; set; }
        public Nullable<decimal> Fund { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTMENT> DEPARTMENT { get; set; }
    }
}
