//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SGROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SGROUP()
        {
            this.LECTURE = new HashSet<LECTURE>();
        }
    
        public int GrpPK { get; set; }
        public Nullable<int> DepFK { get; set; }
        public decimal Num { get; set; }
        public decimal Kurs { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<int> CurFK { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LECTURE> LECTURE { get; set; }
        public virtual TEACHER TEACHER { get; set; }
    }
}
