//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class show_T
    {
        public string name { get; set; }
        public string idcode { get; set; }
        public string id_post { get; set; }
        public string phone { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> rise { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
    }
}
