//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEACHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TEACHER()
        {
            this.LECTURE = new HashSet<LECTURE>();
            this.SGROUP = new HashSet<SGROUP>();
            this.TEACHER1 = new HashSet<TEACHER>();
        }
    
        public int TchPK { get; set; }
        public Nullable<int> DepFK { get; set; }
        public string Name { get; set; }
        public string IDCode { get; set; }
        public int id_Post { get; set; }
        public string Tel { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Rise { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> Chief { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LECTURE> LECTURE { get; set; }
        public virtual POST POST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SGROUP> SGROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEACHER> TEACHER1 { get; set; }
        public virtual TEACHER TEACHER2 { get; set; }
    }
}
